# Homework
## Part 1
1) Compute revenues including tax.
2) Compute final revenues after tax and discount.
3) Create a Boolean list indicating whether revenue > 100.
4) Create a Boolean list indicating whether revenue is between 100 and 300.
5) Add Markdown explanation: Why do parentheses matter in the formula?

In [1]:
revenues = [120, 250, 80, 310, 95]
tax_rate = 0.18
discount_rate = 0.10

In [2]:
revenues = [120,250,80,310,95]
tax_rate = 0.18
revenues_with_tax = [r * (1 + tax_rate) for r in revenues]
revenues_with_tax

[141.6, 295.0, 94.39999999999999, 365.79999999999995, 112.1]

In [3]:
revenues = [120,250,80,310,95]
tax_rate = 0.18
discount_rate = 0.10
final_revenue = [r * (1 + tax_rate) * (1 - discount_rate) for r in revenues]
final_revenue

[127.44, 265.5, 84.96, 329.21999999999997, 100.89]

In [4]:
revenues = [120, 250, 80, 310, 95]

greater_than_100 = [r > 100 for r in revenues]

greater_than_100

[True, True, False, True, False]

In [5]:
revenues =  [120,250,80,310,95]
revenue_between_100_and_300 = [r > 100 and r < 300 for r in revenues]
revenue_between_100_and_300

[True, True, False, False, False]

Parentheses matter because they control the order of operations.

## Part 2
1) Compute total revenue manually using a loop.
2) Compute average revenue.
3) Identify the maximum value without using max().
4) Count how many values are greater than 150.
5) Create a new list of revenues after adding 5% commission.

In [7]:
sales = [120, 250, 80, 310, 95]
total_sales = 0
for s in sales:
    total_sales += s
total_sales

855

In [8]:
sales = [120, 250, 80, 310, 95]
average_revenue = total_sales / len(sales)
average_revenue

171.0

In [11]:
sales = [120,250,80,310,95]
max_value = sales[0]
for s in sales:
    if s > max_value:
     max_value = s
max_value

310

In [12]:
sales = [120,250,80,310,95]
count = 0
for s in sales:
    if s > 150:
        count+=1
count

2

In [14]:
sales = [120,250,80,310,95]
commision_rate = 0.05
sales_with_commision = [s * 1.05 for s in sales]
sales_with_commision

[126.0, 262.5, 84.0, 325.5, 99.75]

## Part 3 
“Premium” if revenue > 250
“Standard” if 100 < revenue ≤ 250
“Low” otherwise
1) Create a list of segment labels.
2) Count how many customers fall into each segment.
3) Add Markdown explanation: Why does the order of elif statements matter?

In [17]:
segments = []

for s in sales:
    if s > 250:
        segments.append("Premium")
    elif 100 < s <= 250:
        segments.append("Standard")
    else:
        segments.append("Low")

segments

['Standard', 'Standard', 'Low', 'Premium', 'Low']

In [19]:
premium_count = 0
standard_count = 0
low_count = 0
  
for segment in segments:
  if segment == "Premium":
   premium_count += 1
  if segment == "Standard":
   standard_count += 1
  if segment == "Low":
   low_count += 1
premium_count, standard_count, low_count

(1, 2, 2)

The order matters because Python checks conditions from top to bottom.

## Part 4
1) Remove duplicates using a set.
2) Convert back to a list.
3) Compare lengths before and after deduplication.
4) Explain in Markdown why sets are unordered.

In [21]:
customer_ids = [1, 2, 3, 3, 4, 5, 5, 6]

In [26]:
customer_ids = [1, 2, 3, 3, 4, 5, 5, 6]
customer_ids_set = set(customer_ids)
customer_ids_set

{1, 2, 3, 4, 5, 6}

In [27]:
customer_ids_list = list(customer_ids)
customer_ids_list

[1, 2, 3, 3, 4, 5, 5, 6]

In [28]:
lists_len = len(customer_ids_list)
sets_len = len(customer_ids_set)
lists_len, sets_len

(8, 6)

Sets are unordered because they are implemented using a hash table.

## Part 5 
Create a dictionary:
1) Add a new key "segment" based on revenue.
2) Update revenue to 300.
3) Remove "city".
4) Loop over the dictionary and print key-value pairs.
5) Add Markdown explanation: Why are dictionaries useful for structured data?

In [29]:
customer = {
    "name": "Anna",
    "revenue": "250",
    "city": "Yerevan"
}

In [34]:
customer["revenue"] = int(customer["revenue"])
if customer["revenue"] > 250:
    customer["segment"] = "Premium"
elif 100 < customer["revenue"] <= 250:
    customer["segment"] = "Standard"
else:
    customer["segment"] = "Low"

customer

{'name': 'Anna', 'revenue': 250, 'city': 'Yerevan', 'segment': 'Standard'}

In [35]:
customer["revenue"] = 300
customer

{'name': 'Anna', 'revenue': 300, 'city': 'Yerevan', 'segment': 'Standard'}

In [36]:
customer.pop("city")
customer

{'name': 'Anna', 'revenue': 300, 'segment': 'Standard'}

In [37]:
for key, value in customer.items():
    print(f"{key}: {value}")

name: Anna
revenue: 300
segment: Standard

Dictionaries are useful because they store key-value pairs, allowing us to label and access data easily.

## Part 6
1) Create a list of revenues after 10% tax.
2) Create a list of revenues greater than 100.
3) Create a list labeling each revenue as:
 “High” if > 200
 “Normal” otherwise
4) Compare list comprehension vs loop in Markdown.

In [38]:
revenues = [120, 250, 80, 310, 95]
tax_rate = 0.1
new_revenues_list = [r * (1 + tax_rate) for r in revenues]
new_revenues_list

[132.0, 275.0, 88.0, 341.0, 104.50000000000001]

In [ ]:
revenues = [120, 250, 80, 310, 95]
revenues_greater_than_100 = [r for r in revenues if r > 100]
revenues_greater_than_100

[120, 250, 310]

In [41]:
revenues = [120, 250, 80, 310, 95]
revenues_labels = ["High" if r > 200 else "Normal" for r in revenues]
revenues_labels

['Normal', 'High', 'Normal', 'High', 'Normal']

In [45]:
labbels = []
for r in revenues:
 if r > 200:
  labbels.append("High")
 else:
  labbels.append("Normal")
labbels

['Normal', 'High', 'Normal', 'High', 'Normal']

## List:
Compact and readable.
Combines iteration, condition, and transformation in one line.
Good for simple transformations.

## Loop
More verbose.
Easier to add multiple steps or debug intermediate values.

## Part 7 
1) Add column "revenue_after_tax".
2) Add column "segment" using conditional logic.
3) Filter rows where revenue > 100.
4) Remove the "revenue_after_tax" column.
5) Print the shape of the DataFrame.
6) Add Markdown explanation: Why is this easier than manual loops?

In [47]:
import pandas as pd
data = {
  "revenue": revenues
 }

df = pd.DataFrame(data)
df

   revenue
0      120
1      250
2       80
3      310
4       95

In [48]:
t = 0.2
df["revenue_after_tax"] = df["revenue"] * (1 - t)
df["revenue_after_tax"]

0     96.0
1    200.0
2     64.0
3    248.0
4     76.0
Name: revenue_after_tax, dtype: float64

In [59]:
df[df["revenue"] > 100]
df[df["revenue_after_tax"] > 100]

   revenue  revenue_after_tax
1      250              200.0
3      310              248.0

In [61]:
df.drop("revenue_after_tax", axis=1)

   revenue
0      120
1      250
2       80
3      310
4       95

In [63]:
df.shape

(5, 2)

## Using a DataFrame is easier than manual loops because:
1) It automatically stores data in structured rows and columns.
2) No need to manually count rows or iterate through data.
3) Operations are faster and more readable.
4) Code is shorter and less error-prone.

## Difference between Mutable and Immutable Objects
1) Mutable objects (e.g., lists, dictionaries) can be changed after creation.
2) Immutable objects (e.g., integers, strings, tuples) cannot be changed; modifying them creates a new object.

## Why Loops Are Less Efficient Than Pandas Vectorization?
1) Loops process elements one by one in Python (slower).
2) Pandas vectorization uses optimized C-based operations that process entire columns at once (faster and more efficient).

## How Boolean Logic Relates to SQL WHERE?

1) Boolean expressions (>, <, ==, and, or) filter data in Python.
SQL WHERE uses the same logical conditions to filter rows.
Example:
df[df["revenue"] > 100] ≈ SELECT * FROM table WHERE revenue > 100

## Why Understanding Lists Helps Understand DataFrames?
1) A DataFrame column behaves like a list/array of values.
2) Filtering, indexing, and iteration concepts come from list logic.
3) Mastering lists makes DataFrame operations easier to understand.