In [1]:
a = 0
type(a)

int

In [2]:
a = -1
type(a)

int

In [3]:
a= -1.58848858848
type(a)

float

In [5]:

pow(2,3)

8

In [1]:
r = 100
t = 0.2
revenue = r * (1+t
               )

In [2]:
revenue

120.0

In [3]:
sales = [100,200,300,400]

In [4]:
sales[0]
sales[-1]

400

In [5]:
sales[0]

100

In [6]:
len(sales)

4

In [8]:
sales.remove(200)

In [9]:
sales

[100, 300, 400]

In [10]:
total = 0
for value in sales:
    total += value

total

800

In [11]:
import pandas as pd

data = {
    "name": ["Anna", "David", "Mariam"],
    "revenue": [150, 220, 90],
    "city": ["Yerevan", "Tbilisi", "Warsaw"]
}

df = pd.DataFrame(data)
df

     name  revenue     city
0    Anna      150  Yerevan
1   David      220  Tbilisi
2  Mariam       90   Warsaw

In [12]:
df.info()
df.shape
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     3 non-null      str
 1   revenue  3 non-null      int64
 2   city     3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

Index(['name', 'revenue', 'city'], dtype='str')

In [13]:
df["revenue"]
df[["name", "revenue"]]

     name  revenue
0    Anna      150
1   David      220
2  Mariam       90

In [14]:
df["revenue"]

0    150
1    220
2     90
Name: revenue, dtype: int64

In [15]:
data

{'name': ['Anna', 'David', 'Mariam'],
 'revenue': [150, 220, 90],
 'city': ['Yerevan', 'Tbilisi', 'Warsaw']}

In [16]:
df.drop("city", axis=1)

     name  revenue
0    Anna      150
1   David      220
2  Mariam       90

In [17]:
data

{'name': ['Anna', 'David', 'Mariam'],
 'revenue': [150, 220, 90],
 'city': ['Yerevan', 'Tbilisi', 'Warsaw']}

In [18]:
df = df.drop("city", axis=1)
df

     name  revenue
0    Anna      150
1   David      220
2  Mariam       90

In [19]:
df

     name  revenue
0    Anna      150
1   David      220
2  Mariam       90

In [20]:
data

{'name': ['Anna', 'David', 'Mariam'],
 'revenue': [150, 220, 90],
 'city': ['Yerevan', 'Tbilisi', 'Warsaw']}

In [21]:
df

     name  revenue
0    Anna      150
1   David      220
2  Mariam       90

In [22]:
df.loc[df["revenue"] < 100, "segment"] = "Low"
df.loc[df["revenue"] >= 100, "segment"] = "High"
df

     name  revenue segment
0    Anna      150    High
1   David      220    High
2  Mariam       90     Low

In [23]:
revenue = 150

if revenue > 100:
    print("High revenue")
else:
    print("Normal revenue")

High revenue

In [24]:
revenue = 90

In [25]:
revenue = 90

if revenue > 100:
    print("High revenue")
else:
    print("Normal revenue")

Normal revenue

In [26]:
sales = [100, 200, 150, 50]

for value in sales:
    if value > 120:
        print("High sale:", value)

High sale: 200
High sale: 150

In [30]:
sales = [100, 200, 150, 50]

for value in sales:
    if value > 120:
        print("High sale:", value)
    if value < 110:
         print("Low Value", value)

Low Value 100
High sale: 200
High sale: 150
Low Value 50

In [31]:
for i in range(5):
    print(i)

0
1
2
3
4

In [32]:
for i in range(3):
    for j in range(2):
        print("i =", i, ", j =", j)

i = 0 , j = 0
i = 0 , j = 1
i = 1 , j = 0
i = 1 , j = 1
i = 2 , j = 0
i = 2 , j = 1

In [35]:

for value in sales:
    print(value)

100
200
150
50

In [36]:
sales = [100, 200, 150]

new_sales = []

for value in sales:
    new_sales.append(value * 1.2)

new_sales

[120.0, 240.0, 180.0]

In [37]:
sales = [100, 200, 150]

new_sales = [value * 1.2 for value in sales]
new_sales

[120.0, 240.0, 180.0]

In [38]:
sales = [100, 200, 150, 50]

high_sales = [value for value in sales if value > 120]
high_sales

[200, 150]

In [39]:
high_sales = []

for value in sales:
    if value > 120:
        high_sales.append(value)

high_sales

[200, 150]

In [40]:
sales = [100, 200, 150, 50]

labels = ["High" if value > 120 else "Low" for value in sales]
labels

['Low', 'High', 'High', 'Low']

In [5]:
a = 6
b = 5
a,b = b,a
print(a)
print(b)

5
6

In [1]:
list = ['data1.csv', 'data2.csv', 'data3.csv']
for  i in list:
  print(f'mer dataneri faylern en {i}')

mer dataneri faylern en data1.csv
mer dataneri faylern en data2.csv
mer dataneri faylern en data3.csv