# Session 4, Advanced Pandas
## Homework
###  P1, Analytical questions after the first merge(products_departments)

In [1]:

import pandas as pd
df_products = pd.read_csv('../data/raw/products.csv')
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [2]:
df_departments_t = pd.read_csv('../data/processed/departments_t.csv')
df_departments_t.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [3]:
# Creating our first merge df for answering questions
df_products_departments = pd.merge(
    df_products,
    df_departments_t,
    on="department_id",
    how="left"
)

df_products_departments.head()

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.8,snacks
1,2,All-Seasons Salt,104,13,9.3,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5,frozen
4,5,Green Chile Anytime Sauce,5,13,4.3,pantry

In [4]:
# Question 1: How many products belong to each department?
df_products_departments["department"].value_counts()

department
personal care      6565
snacks             6264
pantry             5371
beverages          4365
frozen             4007
dairy eggs         3449
household          3085
canned goods       2092
dry goods pasta    1858
produce            1684
bakery             1516
deli               1322
missing            1258
international      1139
breakfast          1116
babies             1081
alcohol            1056
pets                972
meat seafood        907
other               548
bulk                 38
Name: count, dtype: int64

In [5]:
# Question 2: Which departments contain the most products?
df_products_departments["department"].value_counts().head(10)

department
personal care      6565
snacks             6264
pantry             5371
beverages          4365
frozen             4007
dairy eggs         3449
household          3085
canned goods       2092
dry goods pasta    1858
produce            1684
Name: count, dtype: int64

In [6]:
# Question 3: Are products concentrated in a small number of departments?
df_products_departments["department"].value_counts().head(5)

department
personal care    6565
snacks           6264
pantry           5371
beverages        4365
frozen           4007
Name: count, dtype: int64

### P2: Questions unlocked after enriching products

In [7]:
df_aisles = pd.read_csv('../data/raw/aisles.csv')
df_aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [8]:
# Creating our secong merge df for answering questions
df_products_enriched = pd.merge(
    df_products_departments,
    df_aisles,
    on="aisle_id",
    how="left"
)

df_products_enriched.head()

,product_id,product_name,aisle_id,department_id,prices,department,aisle
0,1,Chocolate Sandwich Cookies,61,19,5.8,snacks,cookies cakes
1,2,All-Seasons Salt,104,13,9.3,pantry,spices seasonings
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5,beverages,tea
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5,frozen,frozen meals
4,5,Green Chile Anytime Sauce,5,13,4.3,pantry,marinades meat preparation

In [9]:
# Question 1: How many products belong to each department?
df_products_enriched["department"].value_counts()

department
personal care      6565
snacks             6264
pantry             5371
beverages          4365
frozen             4007
dairy eggs         3449
household          3085
canned goods       2092
dry goods pasta    1858
produce            1684
bakery             1516
deli               1322
missing            1258
international      1139
breakfast          1116
babies             1081
alcohol            1056
pets                972
meat seafood        907
other               548
bulk                 38
Name: count, dtype: int64

In [10]:
# Question 2 How many products belong to each aisle?
df_products_enriched["aisle"].value_counts()

aisle
missing                         1258
candy chocolate                 1246
ice cream ice                   1091
vitamins supplements            1038
yogurt                          1026
                                ...
frozen juice                      47
baby accessories                  44
packaged produce                  32
bulk grains rice dried goods      26
bulk dried fruits vegetables      12
Name: count, Length: 134, dtype: int64

In [11]:
# Question 3 Which aisles are most populated?
df_products_enriched["aisle"].value_counts().head(10)

aisle
missing                 1258
candy chocolate         1246
ice cream ice           1091
vitamins supplements    1038
yogurt                  1026
chips pretzels           989
tea                      894
packaged cheese          891
frozen meals             880
cookies cakes            874
Name: count, dtype: int64

In [12]:
# Question 4: Which departments span the widest variety of products?
df_products_enriched.groupby("department")["product_id"].nunique().sort_values(ascending=False)

department
personal care      6563
snacks             6264
pantry             5371
beverages          4365
frozen             4007
dairy eggs         3449
household          3085
canned goods       2092
dry goods pasta    1858
produce            1684
bakery             1516
deli               1322
missing            1258
international      1139
breakfast          1115
babies             1081
alcohol            1054
pets                972
meat seafood        907
other               548
bulk                 38
Name: product_id, dtype: int64

In [13]:
# Question 5: How are departments and aisles related?
df_products_enriched.groupby("department")["aisle"].nunique().sort_values(ascending=False)

department
personal care      17
pantry             12
frozen             11
snacks             11
household          10
dairy eggs         10
beverages           8
meat seafood        7
alcohol             5
produce             5
dry goods pasta     5
bakery              5
canned goods        5
deli                5
babies              4
breakfast           4
international       4
bulk                2
pets                2
other               1
missing             1
Name: aisle, dtype: int64

### P3: Questions unlocked after this merge(train_transactions)

In [14]:
df_orders_train = pd.read_csv('../data/processed/orders_train.csv')
df_orders_train.head()

,Unnamed: 0,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,10,1187899,1,train,11,4,8,14.0
1,25,1492625,2,train,15,1,11,30.0
2,49,2196797,5,train,5,0,11,6.0
3,74,525192,7,train,21,2,11,6.0
4,78,880375,8,train,4,1,14,10.0

In [15]:
df_order_products_train = pd.read_csv('../data/raw/order_products_train.csv')
df_order_products_train.head()

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [16]:
# Merging our third dataframe(train_transactions)
df_train_transactions = pd.merge(
    df_orders_train,
    df_order_products_train,
    on = "order_id",
    how = "left"
)
df_train_transactions.head()

,Unnamed: 0,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered
0,10,1187899,1,train,11,4,8,14.0,196,1,1
1,10,1187899,1,train,11,4,8,14.0,25133,2,1
2,10,1187899,1,train,11,4,8,14.0,38928,3,1
3,10,1187899,1,train,11,4,8,14.0,26405,4,1
4,10,1187899,1,train,11,4,8,14.0,39657,5,1

In [17]:
# Question 1: How many products are included in each order?
products_per_order = df_train_transactions.groupby("order_id")["product_id"].count().reset_index()
products_per_order.columns = ["order_id", "product_count"]
products_per_order.value_counts()

order_id  product_count
1         8                1
36        8                1
38        9                1
96        7                1
98        49               1
                          ..
3421049   6                1
3421056   5                1
3421058   8                1
3421063   4                1
3421070   3                1
Name: count, Length: 131209, dtype: int64

In [18]:
# Question 2: What is the typical basket size?
df_train_transactions.groupby("order_id").size().value_counts()

5     8895
6     8708
7     8541
4     8218
3     8033
      ...
74       2
80       2
75       1
77       1
67       1
Name: count, Length: 75, dtype: int64

In [19]:
# Question 3: Are larger baskets more common on specific days?
orders_with_products = pd.merge(products_per_order, df_train_transactions[["order_id", "order_dow"]], on="order_id")
basket_by_day = orders_with_products.groupby("order_dow")["product_count"].value_counts()
print(basket_by_day)

order_dow  product_count
0          13               15548
           12               15204
           11               15037
           10               15030
           14               14224
                            ...
6          66                  66
           65                  65
           62                  62
           58                  58
           57                  57
Name: count, Length: 432, dtype: int64

In [20]:
# Question 4: Are reordered items more common at certain times of day?
reorder_by_hour_of_day = df_train_transactions.groupby("order_hour_of_day")["reordered"].mean()
print(reorder_by_hour_of_day)

order_hour_of_day
0     0.571177
1     0.579453
2     0.579665
3     0.581624
4     0.598108
5     0.622823
6     0.650629
7     0.649496
8     0.643353
9     0.623263
10    0.606378
11    0.594423
12    0.587193
13    0.589533
14    0.592201
15    0.583384
16    0.588795
17    0.592177
18    0.584747
19    0.590529
20    0.596921
21    0.607934
22    0.604195
23    0.589979
Name: reordered, dtype: float64

In [21]:
#Question 5: Does basket construction differ across customer order sequence?
basket_with_order_number = pd.merge(
    products_per_order,
    df_train_transactions[["order_id", "order_number"]],
    on = "order_id",
    how = "left"
)
basket_by_sequence = basket_with_order_number.groupby("order_number")["product_count"].mean()
print(basket_by_sequence)

order_number
4      15.607078
5      15.802813
6      16.150482
7      16.202036
8      16.314614
         ...
96     15.157783
97     14.592593
98     13.643836
99     10.704000
100    13.278594
Name: product_count, Length: 97, dtype: float64

### P4: Questions unlocked after final merge(train_transactions)

In [22]:
# Creating our final merge:
df_train_analytic = pd.merge(
    df_train_transactions,
    df_products_enriched,
    on = "product_id",
    how = "left"
)
df_train_analytic.head()

,Unnamed: 0,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,department,aisle
0,10,1187899,1,train,11,4,8,14.0,196,1,1,Soda,77.0,7.0,9.0,beverages,soft drinks
1,10,1187899,1,train,11,4,8,14.0,25133,2,1,Organic String Cheese,21.0,16.0,8.6,dairy eggs,packaged cheese
2,10,1187899,1,train,11,4,8,14.0,38928,3,1,0% Greek Strained Yogurt,120.0,16.0,12.6,dairy eggs,yogurt
3,10,1187899,1,train,11,4,8,14.0,26405,4,1,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,household,paper goods
4,10,1187899,1,train,11,4,8,14.0,39657,5,1,Milk Chocolate Almonds,45.0,19.0,6.8,snacks,candy chocolate

In [23]:
df_train_analytic.columns

Index(['Unnamed: 0', 'order_id', 'user_id', 'eval_set', 'order_number',
       'order_dow', 'order_hour_of_day', 'days_since_prior_order',
       'product_id', 'add_to_cart_order', 'reordered', 'product_name',
       'aisle_id', 'department_id', 'prices', 'department', 'aisle'],
      dtype='str')

In [24]:
#Question 1: Which products are purchased most often?
most_purchased_products = df_train_analytic["product_name"].value_counts()
print(most_purchased_products)

product_name
Banana                                                         18726
Bag of Organic Bananas                                         15480
Organic Strawberries                                           10894
Organic Baby Spinach                                            9784
Large Lemon                                                     8135
                                                               ...
Chewy Reduced Sugar Granola Bars Variety Pack                      1
Plain Flavor Probiotic Acidophilus                                 1
100% Juice, Rio Red Grapefruit                                     1
Puppy Complete Nutrition Chicken & Beef Dinner Wet Dog Food        1
Organic Aromatherapeutic Moroccan Argan Oil Set                    1
Name: count, Length: 39111, dtype: int64

In [25]:
# Question 2: Which departments dominate train orders?
department_counts = df_train_analytic["department"].value_counts()
print(department_counts)

department
produce            409087
dairy eggs         217051
snacks             118862
beverages          113962
frozen             100426
pantry              81242
bakery              48394
canned goods        46799
deli                44291
dry goods pasta     38713
household           35986
meat seafood        30307
breakfast           29552
personal care       21599
babies              14941
international       11902
missing              8251
alcohol              5602
pets                 4497
other                1795
bulk                 1359
Name: count, dtype: int64

In [26]:
# Question 3: Which aisles dominate train orders?
aisles_count = df_train_analytic["aisle"].value_counts()
print(aisles_count)

aisle
fresh vegetables              150609
fresh fruits                  150473
packaged vegetables fruits     78493
yogurt                         55240
packaged cheese                41699
                               ...
kitchen supplies                 448
baby bath body care              328
baby accessories                 306
frozen juice                     294
beauty                           287
Name: count, Length: 134, dtype: int64

In [27]:
# Question 4: Which departments have the highest reorder rates?
departments_by_reorder_rate = df_train_analytic.groupby("department")["reordered"].mean().sort_values(ascending = False)
print(departments_by_reorder_rate)

department
dairy eggs         0.674966
produce            0.664617
beverages          0.658132
bakery             0.634211
pets               0.630198
deli               0.617891
alcohol            0.606748
meat seafood       0.590854
snacks             0.581363
bulk               0.578366
breakfast          0.571806
frozen             0.559297
babies             0.541062
dry goods pasta    0.487821
canned goods       0.486805
household          0.427166
other              0.388301
missing            0.381530
international      0.379936
pantry             0.363088
personal care      0.337516
Name: reordered, dtype: float64

In [28]:
# Question 5: Which aisles appear most often in large baskets?
basket_sizes = df_train_transactions.groupby("order_id")["product_id"].count().reset_index()
basket_sizes.columns = ["order_id", "basket_size"]
large_baskets = basket_sizes[basket_sizes["basket_size"] > 10]
print(large_baskets)

        order_id  basket_size
4             98           49
5            112           11
6            170           17
8            226           13
9            349           11
...          ...          ...
131195   3420857           12
131197   3420894           24
131198   3420895           16
131201   3420996           11
131202   3420998           28

[52848 rows x 2 columns]

In [29]:
large_basket_products = pd.merge(
    large_baskets,
    df_train_transactions,
    on="order_id",
    how="inner"
)
print(large_basket_products)

        order_id  basket_size  Unnamed: 0  user_id eval_set  order_number  \
0             98           49      941403    56463    train            41
1             98           49      941403    56463    train            41
2             98           49      941403    56463    train            41
3             98           49      941403    56463    train            41
4             98           49      941403    56463    train            41
...          ...          ...         ...      ...      ...           ...
955203   3420998           28     2051789   123299    train            25
955204   3420998           28     2051789   123299    train            25
955205   3420998           28     2051789   123299    train            25
955206   3420998           28     2051789   123299    train            25
955207   3420998           28     2051789   123299    train            25

        order_dow  order_hour_of_day  days_since_prior_order  product_id  \
0               3                  8                    14.0        8859
1               3                  8                    14.0       19731
2               3                  8                    14.0       43654
3               3                  8                    14.0       13176
4               3                  8                    14.0        4357
...           ...                ...                     ...         ...
955203          6                 18                    30.0       16185
955204          6                 18                    30.0        6719
955205          6                 18                    30.0       41950
955206          6                 18                    30.0        8174
955207          6                 18                    30.0        7615

        add_to_cart_order  reordered
0                       1          1
1                       2          1
2                       3          1
3                       4          1
4                       5          1
...                   ...        ...
955203                 24          0
955204                 25          0
955205                 26          0
955206                 27          0
955207                 28          0

[955208 rows x 12 columns]

In [31]:
large_basket_products = pd.merge(
    large_basket_products,
    df_products[["product_id", "aisle_id"]],
    on = "product_id",
    how = "left"
)

In [33]:
large_basket_products = pd.merge(
    large_basket_products,
    df_aisles,
    on = "aisle_id",
    how = "left"
)

In [34]:
aisles_in_large_baskets = large_basket_products["aisle"].value_counts()
print(aisles_in_large_baskets)

aisle
fresh vegetables              113774
fresh fruits                  103149
packaged vegetables fruits     56042
yogurt                         40677
packaged cheese                30552
                               ...
baby bath body care              213
baby accessories                 207
frozen juice                     194
beauty                           156
specialty wines champagnes       145
Name: count, Length: 134, dtype: int64

In [38]:
#Question 6: At what times are certain departments purchased more frequently?
department_by_hour = df_train_analytic.groupby(["order_hour_of_day", "department"])["product_id"].count()
department_by_hour = department_by_hour.reset_index().sort_values(["order_hour_of_day", "product_id"], ascending=[True,False])
print(department_by_hour)

     order_hour_of_day     department  product_id
19                   0        produce        2782
7                    0     dairy eggs        1331
20                   0         snacks         759
3                    0      beverages         693
10                   0         frozen         692
..                 ...            ...         ...
494                 23  international         133
482                 23        alcohol          41
497                 23          other          32
500                 23           pets          31
487                 23           bulk          20

[503 rows x 3 columns]