# Dates

In [9]:
import pandas as pd
from datetime import datetime, date, timedelta

In [35]:
 my_date = date(year = 2025, month = 3, day = 24)

In [37]:
my_date

datetime.date(2025, 3, 24)

In [38]:
type(my_date)

datetime.date

In [39]:
my_time = date(year=2026,month=3, day = 24)

In [40]:
today = date.today()
today

datetime.date(2026, 3, 24)

In [41]:
now = datetime.now()
now

datetime.datetime(2026, 3, 24, 20, 11, 13, 458570)

In [42]:
my_date.strftime("%Y-%m-%d")

'2025-03-24'

In [43]:
my_date.strftime("%Y/%m/%d")

'2025/03/24'

In [44]:
my_date.strftime("%B-%d-%Y")

'March-24-2025'

In [45]:
my_date.strftime("%b-%d-%y")

'Mar-24-25'

In [54]:
start_date = my_date
end_date = datetime(2026,4,4)

In [48]:
delta = end_date - start_date
delta

datetime.timedelta(days=376)

In [52]:
end_date + delta
end_date + timedelta(weeks = 1)

datetime.date(2026, 4, 11)

In [55]:
end_date + timedelta(days = 1, seconds=36)

datetime.datetime(2026, 4, 5, 0, 0, 36)

# Dates with Pandas

In [63]:
import pandas as pd

df_dates = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105],
    "signup_date": ["2024-01-15", "2024-02-20", "2024-03-05", "2024-03-18", "2024-04-10"],
    "last_purchase": ["2024-06-01", "2024-06-15", "2024-07-01", "2024-07-08", "2024-07-12"]
})

df_dates

   customer_id signup_date last_purchase
0          101  2024-01-15    2024-06-01
1          102  2024-02-20    2024-06-15
2          103  2024-03-05    2024-07-01
3          104  2024-03-18    2024-07-08
4          105  2024-04-10    2024-07-12

In [64]:
df_dates.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   signup_date    5 non-null      str
 2   last_purchase  5 non-null      str
dtypes: int64(1), str(2)
memory usage: 352.0 bytes

In [66]:
df_dates["signup_date"] = pd.to_datetime(df_dates["signup_date"])
df_dates["last_purchase"] = pd.to_datetime(df_dates["last_purchase"])

df_dates.dtypes

customer_id               int64
signup_date      datetime64[us]
last_purchase    datetime64[us]
dtype: object

In [69]:
df_dates["signup_year"] = df_dates["signup_date"].dt.is_year_start
df_dates

   customer_id signup_date last_purchase  signup_year
0          101  2024-01-15    2024-06-01        False
1          102  2024-02-20    2024-06-15        False
2          103  2024-03-05    2024-07-01        False
3          104  2024-03-18    2024-07-08        False
4          105  2024-04-10    2024-07-12        False

In [71]:
df_dates["signup_day"] = df_dates["signup_date"].dt.day
df_dates

   customer_id signup_date last_purchase  signup_year  signup_day
0          101  2024-01-15    2024-06-01        False          15
1          102  2024-02-20    2024-06-15        False          20
2          103  2024-03-05    2024-07-01        False           5
3          104  2024-03-18    2024-07-08        False          18
4          105  2024-04-10    2024-07-12        False          10

In [73]:
df_dates["signup_month_name"] = df_dates["signup_date"].dt.month_name()
df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_day,signup_month_name
0,101,2024-01-15,2024-06-01,False,15,January
1,102,2024-02-20,2024-06-15,False,20,February
2,103,2024-03-05,2024-07-01,False,5,March
3,104,2024-03-18,2024-07-08,False,18,March
4,105,2024-04-10,2024-07-12,False,10,April

In [74]:
df_dates["signup_day_name"] = df_dates["signup_date"].dt.day_name()
df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_day,signup_month_name,signup_day_name
0,101,2024-01-15,2024-06-01,False,15,January,Monday
1,102,2024-02-20,2024-06-15,False,20,February,Tuesday
2,103,2024-03-05,2024-07-01,False,5,March,Tuesday
3,104,2024-03-18,2024-07-08,False,18,March,Monday
4,105,2024-04-10,2024-07-12,False,10,April,Wednesday

In [80]:
df_dates["is_weekend"] = (df_dates['signup_date'].dt.day_of_week >= 5).astype(int)
df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_day,signup_month_name,signup_day_name,is_weekend
0,101,2024-01-15,2024-06-01,False,15,January,Monday,0
1,102,2024-02-20,2024-06-15,False,20,February,Tuesday,0
2,103,2024-03-05,2024-07-01,False,5,March,Tuesday,0
3,104,2024-03-18,2024-07-08,False,18,March,Monday,0
4,105,2024-04-10,2024-07-12,False,10,April,Wednesday,0

In [87]:
df_dates['days_between_signup_purchase']=df_dates['last_purchase'] - df_dates['signup_date']
df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_day,signup_month_name,signup_day_name,is_weekend,days_between_signup_purch,days_between_signup_purchase
0,101,2024-01-15,2024-06-01,False,15,January,Monday,0,-138 days,138 days
1,102,2024-02-20,2024-06-15,False,20,February,Tuesday,0,-116 days,116 days
2,103,2024-03-05,2024-07-01,False,5,March,Tuesday,0,-118 days,118 days
3,104,2024-03-18,2024-07-08,False,18,March,Monday,0,-112 days,112 days
4,105,2024-04-10,2024-07-12,False,10,April,Wednesday,0,-93 days,93 days

In [90]:
df_dates.sort_values('signup_date', ascending=False)

,customer_id,signup_date,last_purchase,signup_year,signup_day,signup_month_name,signup_day_name,is_weekend,days_between_signup_purch,days_between_signup_purchase
4,105,2024-04-10,2024-07-12,False,10,April,Wednesday,0,-93 days,93 days
3,104,2024-03-18,2024-07-08,False,18,March,Monday,0,-112 days,112 days
2,103,2024-03-05,2024-07-01,False,5,March,Tuesday,0,-118 days,118 days
1,102,2024-02-20,2024-06-15,False,20,February,Tuesday,0,-116 days,116 days
0,101,2024-01-15,2024-06-01,False,15,January,Monday,0,-138 days,138 days

In [92]:
list(pd.date_range(start="2024-07-01", periods=7, freq="D"))

[Timestamp('2024-07-01 00:00:00'),
 Timestamp('2024-07-02 00:00:00'),
 Timestamp('2024-07-03 00:00:00'),
 Timestamp('2024-07-04 00:00:00'),
 Timestamp('2024-07-05 00:00:00'),
 Timestamp('2024-07-06 00:00:00'),
 Timestamp('2024-07-07 00:00:00')]

In [93]:
import pandas as pd

some_date = pd.Timestamp("2024-07-15")

print(f"Original date: {some_date}")
print(f"Beginning of month: {some_date.to_period('M').start_time}")
print(f"End of month: {some_date.to_period('M').end_time}")

Original date: 2024-07-15 00:00:00
Beginning of month: 2024-07-01 00:00:00
End of month: 2024-07-31 23:59:59.999999

In [96]:
df_dates['bom'] = df_dates['signup_date'].dt.to_period('M').dt.start_time.dt.date
df_dates['eom'] = df_dates['signup_date'].dt.to_period('M').dt.end_time.dt.date
df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_day,signup_month_name,signup_day_name,is_weekend,days_between_signup_purch,days_between_signup_purchase,bom,eom
0,101,2024-01-15,2024-06-01,False,15,January,Monday,0,-138 days,138 days,2024-01-01,2024-01-31
1,102,2024-02-20,2024-06-15,False,20,February,Tuesday,0,-116 days,116 days,2024-02-01,2024-02-29
2,103,2024-03-05,2024-07-01,False,5,March,Tuesday,0,-118 days,118 days,2024-03-01,2024-03-31
3,104,2024-03-18,2024-07-08,False,18,March,Monday,0,-112 days,112 days,2024-03-01,2024-03-31
4,105,2024-04-10,2024-07-12,False,10,April,Wednesday,0,-93 days,93 days,2024-04-01,2024-04-30