In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

In [ ]:
def csv_downloader(URL, name, path):
    df = pd.read_csv(URL)
    df.to_csv(f"{path}/{name}",index=False)
    prstr(f'{name} have been successfully saved in {path}')
    prstr(f"The size of the data {df.shape}")
    return df

In [13]:
df_orders = csv_downloader(URL = 'https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/rfm/orders.csv',
                    name = 'orders',
                    path = '../data/rfm')

orders have been successfully saved in ../data/rfm
The size of the data (4906, 3)

In [29]:
df_orders = pd.read_csv('../data/rfm/orders.csv', parse_dates = ['order_date'])

In [31]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 4906 entries, 0 to 4905
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  4906 non-null   str
 1   order_date   4906 non-null   datetime64[us]
 2   revenue      4906 non-null   int64
dtypes: datetime64[us](1), int64(1), str(1)
memory usage: 189.5 KB

In [ ]:
#RFM

In [26]:
fig = px.histogram(data_frame=df_orders,
             x = 'revenue',
             title = 'Revenue Distribution',
             nbins = 40
             )
fig.update_layout(
    xaxis_title = 'Revenue',
    yaxis_title = 'Count'
)
fig.show()

## RFM
1. max_date() > Recency
2. max_date - customer last day
3. count() - frequens
4. SUM revenue

In [34]:
max_date = df_orders['order_date'].max()
rfm = df_orders.groupby('customer_id').agg(
    {
      'order_date': lambda date: (max_date - date.max()).days,
      'customer_id': lambda num: len(num),
      'revenue': lambda rev: rev.sum()
    
    }
)

In [33]:
df_orders.head()

           customer_id order_date  revenue
0  Mr. Brion Stark Sr. 2004-12-20       32
1       Ethyl Botsford 2005-05-02       36
2       Hosteen Jacobi 2004-03-06      116
3        Mr. Edw Frami 2006-03-15       99
4          Josef Lemke 2006-08-14       76

In [35]:
rfm.head()

                    order_date  customer_id  revenue
customer_id
Abbey O'Reilly DVM         204            6      472
Add Senger                 139            3      340
Aden Lesch Sr.             193            4      405
Admiral Senger             131            5      448
Agness O'Keefe              89            9      843

In [37]:
# rfm.rename({})
column_names = ['Recency', 'Frequency', 'Monetary']
rfm.columns = column_names

In [38]:
rfm.head()

                    Recency  Frequency  Monetary
customer_id
Abbey O'Reilly DVM      204          6       472
Add Senger              139          3       340
Aden Lesch Sr.          193          4       405
Admiral Senger          131          5       448
Agness O'Keefe           89          9       843

In [39]:
rfm.reset_index(inplace = True)

In [40]:
rfm.head()

          customer_id  Recency  Frequency  Monetary
0  Abbey O'Reilly DVM      204          6       472
1          Add Senger      139          3       340
2      Aden Lesch Sr.      193          4       405
3      Admiral Senger      131          5       448
4      Agness O'Keefe       89          9       843

In [ ]:
pd.qcut()

list[range(1, 2, 3)]

In [56]:
some_range = [i for i in range(8)]
print(some_range)
example = pd.qcut(some_range, 3, labels=["bad", "medium", "good"])
example

[0, 1, 2, 3, 4, 5, 6, 7]

['bad', 'bad', 'bad', 'medium', 'medium', 'good', 'good', 'good']
Categories (3, str): ['bad' < 'medium' < 'good']

In [57]:
rfm['R'] = pd.qcut(rfm['Recency'],4, ['4','3','2','1'])
rfm['F'] = pd.qcut(rfm['Frequency'],4, ['1','2','3','4'])
rfm['M'] = pd.qcut(rfm['Monetary'],4, ['1','2','3','4'])

In [58]:
rfm.head()

          customer_id  Recency  Frequency  Monetary  R  F  M
0  Abbey O'Reilly DVM      204          6       472  3  3  3
1          Add Senger      139          3       340  3  1  2
2      Aden Lesch Sr.      193          4       405  3  2  2
3      Admiral Senger      131          5       448  4  2  3
4      Agness O'Keefe       89          9       843  4  4  4

In [61]:
px.histogram(data_frame = rfm,
             x = 'M' )

In [62]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [69]:
fig = make_subplots(
    rows = 1,
    cols = 3,
    subplot_titles = ('R', 'F', 'M')
)
fig.add_trace(
    go.Histogram(x = rfm['Recency']),
    row = 1,
    col = 1
)
fig.add_trace(
    go.Histogram(x = rfm['Frequency']),
    row = 1,
    col = 2
)
fig.add_trace(
    go.Histogram(x = rfm['Monetary']),
    row = 1,
    col = 3
)
fig.update_layout(title = "Recency, Frequency, Monetory",
                  showlegend = False)
fig.update_xaxes(title_text = 'Recency', row = 1, col = 1)
fig.update_xaxes(title_text = 'Frequency', row = 1, col = 2)
fig.update_xaxes(title_text = 'Monetory', row = 1, col = 3)

fig.show()

In [ ]:
# STRING_AGG()

In [81]:
rfm['RFM_Segment'] = rfm['R'].astype(str) + rfm['F'].astype(str) + rfm['M'].astype(str)
rfm.head()

,customer_id,Recency,Frequency,Monetary,R,F,M,RFM_Score,RFM_Segment
0,Abbey O'Reilly DVM,204,6,472,3,3,3,333,333
1,Add Senger,139,3,340,3,1,2,312,312
2,Aden Lesch Sr.,193,4,405,3,2,2,322,322
3,Admiral Senger,131,5,448,4,2,3,423,423
4,Agness O'Keefe,89,9,843,4,4,4,444,444

In [82]:
rfm_segments = (
    rfm[['customer_id', 'RFM_Segment']]
    .groupby('RFM_Segment')
    .count()
)

rfm_segments.reset_index(inplace=True)

  RFM_Segment  customer_id
0         111           90
1         112           31
2         113            6
3         121           11
4         122           29